// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAybWruvdYBgyq8expaooc-Z0TgMJlalmw',
    appId: '1:45446423002:web:c59c090154e2db8e65e0e3',
    messagingSenderId: '45446423002',
    projectId: 'freshiifarm',
    authDomain: 'freshiifarm.firebaseapp.com',
    storageBucket: 'freshiifarm.firebasestorage.app',
    measurementId: 'G-RHM4MNHF67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKIBlLKCIll1Z59aV-HRvQLFlJerOBzSs',
    appId: '1:45446423002:android:c31a4719496a5a0565e0e3',
    messagingSenderId: '45446423002',
    projectId: 'freshiifarm',
    storageBucket: 'freshiifarm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3JNY6rsU3j_uBn3Spj4cmMckHH1hZmws',
    appId: '1:45446423002:ios:cac63e5f66dfc0b565e0e3',
    messagingSenderId: '45446423002',
    projectId: 'freshiifarm',
    storageBucket: 'freshiifarm.firebasestorage.app',
    iosBundleId: 'com.example.freshiifarmMain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3JNY6rsU3j_uBn3Spj4cmMckHH1hZmws',
    appId: '1:45446423002:ios:cac63e5f66dfc0b565e0e3',
    messagingSenderId: '45446423002',
    projectId: 'freshiifarm',
    storageBucket: 'freshiifarm.firebasestorage.app',
    iosBundleId: 'com.example.freshiifarmMain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAybWruvdYBgyq8expaooc-Z0TgMJlalmw',
    appId: '1:45446423002:web:a4cbeb8e9524771565e0e3',
    messagingSenderId: '45446423002',
    projectId: 'freshiifarm',
    authDomain: 'freshiifarm.firebaseapp.com',
    storageBucket: 'freshiifarm.firebasestorage.app',
    measurementId: 'G-YTXCKDM54V',
  );

}